name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-m-16

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.XREPO_GITHUB_TOKEN}}
          submodules: recursive

      - name: Install Foundry
        run: |
          curl -sSL https://raw.githubusercontent.com/thrackle-io/foundry/refs/heads/master/foundryup/foundryup -o $HOME/foundryup
          FOUNDRY_DIR=$HOME/foundry bash $HOME/foundryup --version $(awk '$1~/^[^#]/' script/foundryScripts/foundry.lock)
          echo "$HOME/foundry/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          forge clean && forge build --optimize